replicaCount: 2

image:
  repository: harbor.example.com/library/petclinic
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: petclinic.lab.local
