replicaCount: 1

image:
  repository: harbor.mtahatavaci.site/library/petclinic
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: petclinic.mtahatavaci.site
  tls: true
  secretName: petclinic-tls

